### ISSUE TITLE
Implement initial bark-container

### ISSUE THREAD

**Issue by entelecheia** [entelecheia/bark-container#1]
## Summary

Implement a Docker container to run the Bark text-to-speech engine.

## Tasks

- [ ] Create Dockerfile
  - Use Python base image
  - Install Bark and dependencies
- [ ] Copy Bark code into image
- [ ] Create entrypoint script
  - Start Bark server on container startup
- [ ] Include base Bark models
  - English, Mandarin, Spanish, etc
- [ ] Create config volume
  - For custom Bark config files
- [ ] Create data volume
  - For caching downloaded models
- [ ] Write README
  - Usage
  - Models
  - Volumes
  - Configs
  
## Requirements

- Dockerfile builds Bark server image
- Entrypoint launches Bark server on start
- Base models included for major languages
- Config and data volumes for customization
- README explains usage and configuration

## Resources

- Bark repo: https://github.com/suno-ai/bark
